[package]
name = "postamble-motif"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
enum2str = "0.1.16"
rand = "0.9.1"
shapemaker = { version = "1.2.2", path = "../.." }
svg = "0.18.0"
