[package]
name = "schedule-hell-backbone"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
ffmpeg-next = "7.1.0"
rand = "0.9.0"
shapemaker = { version = "1.2.2", path = "../.." }
