[package]
name = "schedule-hell"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
itertools = "0.14.0"
pico-args = { version = "0.5.0", features = ["combined-flags", "eq-separator"] }
rand = "0.9.0"
shapemaker = { path = "../..", features = ["mp4"] }
