on:
  pull_request: {}

jobs:
  perf-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install system deps for ffmpeg-sys-next
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable }
      - uses: Swatinem/rust-cache@v2
      - uses: extractions/setup-just@v1
      - uses: carlosperate/download-file-action@v2
        with:
          {
            file-url: "https://gwennlbh.github.io/shapemaker/timings.csv",
            file-name: results-main.csv,
          }
      # - uses: fontist/setup-fontist@v2
      # - run: fontist install "Victor Mono"
      - run: just timings results-main.csv
      - id: video
        uses: actions/upload-artifact@v4
        with:
          name: output-video
          path: out.mp4
          if-no-files-found: error
          compression-level: 0
          overwrite: true
      - id: results_csv
        uses: juliangruber/read-file-action@v1
        with: { path: ./results.csv }
      - id: results_table
        uses: petems/csv-to-md-table-action@master
        with: { csvinput: "${{ steps.results_csv.outputs.content }}" }
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        # create or update a comment on the PR with the results
        uses: edumserrano/find-create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body-includes: <!-- PERF TIMING RESULTS COMMENT -->
          body: |
            <!-- PERF TIMING RESULTS COMMENT -->
            ### Performance Timings

            ${{ steps.results_table.outputs.markdown-table }}

            ### Resulting video

            ${{ steps.video.outputs.artifact-url }}
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install system deps for ffmpeg-sys-next
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable }
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with: { command: check, args: --workspace }
      - uses: actions-rs/cargo@v1
        with: { command: check, args: --no-default-features --features web }

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install system deps for ffmpeg-sys-next
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable }
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with: { command: test, args: --workspace }
