on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:7.1-ubuntu2404
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable }
      - uses: actions-rs/cargo@v1
        with: { command: doc, args: --no-deps }
      - uses: extractions/setup-just@v2
      - uses: fontist/setup-fontist@v2
      - run: fontist install "Victor Mono"
      - run: just timings
      - name: publish results.csv as timings.csv
        run: cp results.csv target/doc/timings.csv
      - name: make / redirect to /shapemaker/index.html
        run: |
          echo '<meta http-equiv="refresh" content="0; url=shapemaker/index.html">' > target/doc/index.html
      - name: Deploy with gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: true
          publish_dir: target/doc
          github_token: "${{ secrets.GITHUB_TOKEN }}"
