on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install system deps for ffmpeg-sys-next
        run: |
          sudo apt update
          sudo apt install -y \
            pkg-config \
            clang  \
            libavcodec-dev  \
            libavdevice-dev  \
            libavfilter-dev  \
            libavformat-dev  \
            libswresample-dev \
            libavutil-dev  \
            libpostproc-dev \
            libswscale-dev
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable }
      - uses: actions-rs/cargo@v1
        with: { command: doc, args: "--no-deps --target-dir docs" }
      - name: Deploy with gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: true
          publish_dir: docs
          github_token: "${{ secrets.GITHUB_TOKEN }}"
